config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "pages#home"
  get 'pages/home', to: 'pages#home'


  resources :recipes

  get '/signup', to: 'chefs#new'
  resources :chefs, except: [:new]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
end

app/models/chef.rb
class Chef < ApplicationRecord
  before_save {self.email = email.downcase}
  validates :chefname, presence: true, length: {minimum: 5, maximum: 50}
  validates :email, presence: true, length: {minimum: 5, maximum: 50},
            uniqueness: true,
            format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i,
                    message: "Invalid format for email address"}
    has_many :recipes, dependent: :destroy
    has_secure_password
    validates :password, presence: true, length: {minimum: 5, maximum: 50}, allow_nil: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
validates :name, presence: true
validates :description, presence: true, length: {minimum: 5, maximum: 500}
belongs_to :chef
validates :chef_id, presence: true
default_scope -> {order(updated_at: :desc)}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_chef, :logged_in?

  def current_chef
    @current_chef ||= Chef.find(session[:chef_id]) if session[:chef_id]
  end

  def logged_in?
    !!current_chef
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to root_path
    end
  end

end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController
  before_action :set_chef, only: [:show, :edit, :update, :delete]

  def index
    @chefs = Chef.paginate(page: params[:page], per_page: 5)
  end

  def new
      @chef = Chef.new
  end

  def create
     @chef = Chef.new(chef_params)
     if @chef.save
       session[:chef_id] = @chef.id
      flash[:success] = "Welcome #{@chef.chefname}!"
       redirect_to chef_path(@chef)
     else
       render 'new'
     end
  end

  def show
    @chef_recipes = @chef.recipes.paginate(page: params[:page], per_page: 5)
  end

  def edit
  end

  def update
    if @chef.update(chef_params)

      flash[:succes] = "Your account was successfully updated"
      redirect_to @chef
    else
      render 'edit'
    end
  end

  def destroy
    @chef.destroy
    flash[:danger] = "Chef and associated recipes have been deleted"
    redirect_to chefs_path
  end

  private

  def chef_params
    params.require(:chef).permit(:chefname, :email, :password, :password_confirmation)
  end

  def set_chef
    @chef = Chef.find(params[:id])  
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    redirect_to recipes_path if logged_in?
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update]

def index
  @recipes = Recipe.paginate(page: params[:page], per_page: 5)
end

def show
end

def new
  @recipe = Recipe.new
end

def create
  @recipe = Recipe.new(recipe_params)
  @recipe.chef = Chef.current_chef
  if @recipe.save
    flash[:success] = "Recipe was created successfully!"
    redirect_to recipe_path(@recipe)
  else
    render 'new'
  end
end

def edit
  if @recipe.save
  else
    render 'edit'
  end
end

def update
  if @recipe.update(recipe_params)
    flash[:success] = "Recipe was updated successfully!"
    redirect_to recipe_path(@recipe)
    else
  render 'edit'
  end
end

def destroy
    @recipe = Recipe.find(params[:id]).destroy
    flash[:success] = "Recipe deleted!"
    redirect_to recipes_path
end


private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

    def recipe_params
      params.require(:recipe).permit(:name, :description)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    chef = Chef.find_by(email: params[:session][:email].downcase)
    if chef && chef.authenticate(params[:session][:password])
      session[:chef_id] = chef.id
      flash[:success] = "You have successfully logged in"
      redirect_to chef
    else
    flash.now[:danger] = "There was something wrong with your login information"
      render 'new'
    end
  end

  def destroy
    session[:chef_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = { size: 80 })
  gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
  size = options[:size]
  gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  image_tag(gravatar_url, alt: user.chefname,
                            class: "img-circle")
end

end

app/views/chefs/_form.html.erb
<%= render 'shared/errors', obj: @chef %>

<div class="row">
  <div class="col-md-12 ">
    <%= form_for(@chef, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-md-2 colormatch">
          <%= f.label :chefname, "Name" %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :chefname, class: "form-control", placeholder: "Enter your Name", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-md-2 colormatch">
          <%= f.label :email %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :email, class: "form-control", placeholder: "Enter your email" %>
        </div>
      </div>
      <div class="form-group">
      <div class="control-label col-md-2 colormatch">
        <%= f.label :password %>
      </div>
      <div class="col-md-8">
        <%= f.password_field :password, class: "form-control", placeholder: "Enter a password" %>
      </div>
    </div>
    <div class="form-group">
    <div class="control-label col-md-2 colormatch">
      <%= f.label :password_confirmation, "Confirm Password" %>
    </div>
    <div class="col-md-8">
      <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirm your password" %>
    </div>
  </div>
  </div>
      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= f.submit(@chef.new_record? ? "Create Account" : "Confirm Changes",
              class:  "btn btn-primary btn-lg btn-xlarge") %>
        </div>
      </div>
    <% end %>
    <div class="col-md-4 col-md-offset-4 colormatch">
      [ <%= link_to "Cancel request", chefs_path %> ]
    </div>
  </div>
</div>

app/views/chefs/edit.html.erb
<%= render 'shared/page_title', title: "Edit Your Profile" %>

<%= render 'form' %>

app/views/chefs/index.html.erb
<%= render 'shared/page_title', title: "showing all chefs" %>

<div align="center">
  <% will_paginate %>
  <% @chefs.each do |chef| %>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
          <li><%= link_to gravatar_for(chef), chef_path(chef) %></li>
          <li class="chef-title"><%= link_to chef.chefname.capitalize,
                                         chef_path(chef) %></li>
    <li><small><%= pluralize(chef.recipes.count, "recipe") if chef.recipes %>
            </small></li>
            <li> <%= link_to "Delete this chef", chef_path(chef), method: :delete,
            data: {confirm: "Are you sure?"}%></li>
        </div>
      </div>
    </ul>
  <% end %>
    <% will_paginate %>
</div>

app/views/chefs/new.html.erb
<%= render 'shared/page_title', title: "Sign Up" %>

<%= render 'form' %>

app/views/chefs/show.html.erb
<%= render 'shared/page_title', title: "#{@chef.chefname.capitalize}'s Profile" %>

<div class="row">
  <div class="col-md-4 col-md-offset-4 centre">
    <%= gravatar_for @chef, size: 100 %>
  </div>
</div>

<h4 align="center"> <%= @chef.chefname %>'s recipes</h4>
  <div align="center">
    <%= will_paginate @chef_recipes %>
</div>
<%= render 'recipes/recipe', obj: @chef_recipes %>
<div align="center">
  <%= will_paginate @chef_recipes %>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
 <p>My Recipes by Louise</p>
</div> 

app/views/layouts/_messages.html.erb
<div class="row"
  <div class="col-md-10 col-md-offset-1">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name %>">
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= msg %>
      </div>
    <%end%>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<ul>
  <li><%= link_to "The Simpson Table", root_path, id: "logo" %> </li>
    <li><%= link_to "Create a new Recipe", new_recipe_path %></li>
    <li><%= link_to "View all Recipes", recipes_path %></li>
    <li> <%= link_to "Chefs", chefs_path %></li>
    <!-- need to fix the search bar -->
    <li><form class="navbar-form navbar-left">
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Search">
      </div>
      <button type="submit" class="btn btn-default">Submit</button>
    </form></li>

    <div class="dropdown">
      <button class="dropbtn">Recipes</a>
      <div class="dropdown-content">
      <a href"<%= link_to new_recipe_path %>">Create a new Recipe</a>
      <a href"<%= link_to recipes_path %>">View all Recipes</a>
    </div>
  </li>

    <li style="float:right"><%= link_to 'Log in', login_path %></li>
    <li style="float:right"><%= link_to 'Log out', logout_path, method: :delete %></li>
  </ul>

app/views/layouts/_navigation2.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "MyRecipes", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-collapse">

      <ul class="nav navbar-nav">
        <li> <%= link_to "Chefs", chefs_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Recipes <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Create a new Recipe", new_recipe_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "View all Recipes", recipes_path %></li>
          </ul>
        </li>
      </ul>

      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Log in', login_path %></li>
        <li><%= link_to 'Log out', logout_path, method: :delete %></li>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myrecipes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron centre">
  <h1> Welcome to My Recipes! </h1>
  <p><%= link_to "Sign up or Log in", signup_path, class: "btn btn-primary btn-xlarge" %></p>
</div>

app/views/recipes/_form.html.erb
<%= render 'shared/errors', obj: @recipe %>

<div class="row">
  <div class="col-md-12 ">
    <%= form_for(@recipe, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-md-2 colormatch">
          <%= f.label :name %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :name, class: "form-control", placeholder: "Name of recipe", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-md-2 colormatch">
          <%= f.label :description %>
        </div>
        <div class="col-md-8">
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Enter steps to create recipe" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= f.submit class: "btn btn-primary btn-lg btn-xlarge" %>
        </div>
      </div>
    <% end %>
    <div class="col-md-4 col-md-offset-4 colormatch">
      [ <%= link_to "Cancel request", recipes_path %> ]
    </div>
  </div>
</div>

app/views/recipes/_recipe.html.erb
<% obj.each do |recipe| %>
  <div class="row">
    <div class="col-md-2">
      <section class="center">

      </section>
    </div>

    <div class="col-md-8 well">
      <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
        <p><%= truncate(recipe.description, length: 150) %></p>
        <p>
        <hr/>
        <span class="quiet">
          <small>
            Created <%= time_ago_in_words(recipe.created_at) %> ago
          </small>
        </span>
      </p>
    </div>
  </div>

<%end%>

app/views/recipes/edit.html.erb
<%= render 'shared/page_title', title: "Edit a Recipe" %>

<%= render 'form' %>

app/views/recipes/index.html.erb
<%= render 'shared/page_title', title: "All Recipes" %>

<div align="center">
<%= will_paginate %>
</div>
<%= render 'recipe', obj: @recipes %>
<div align="center">
<%= will_paginate %>
</div>

app/views/recipes/new.html.erb
<%= render 'shared/page_title', title: "Create a New Recipe" %>

<%= render 'form' %>

app/views/recipes/show.html.erb
<%= render 'shared/page_title', title: "Recipe: " + @recipe.name.capitalize %>

<div class="well col-md-8 col-md-offset-2">
  <h4 class="center description"><strong>Description: </strong><h4>
<hr />
  <div class="para"><%= simple_format(@recipe.description) %></div>
<hr />
  <p class="center">
  <p> Created by: </p>
  <p class="center">
    <%= link_to gravatar_for(@recipe.chef), recipes_path %>
    <div class="center"><small><%= @recipe.chef.chefname %></small>
      <p>
    <small> Created <%= time_ago_in_words(@recipe.created_at) %> ago</small>
   </div>
   <div class="recipe-actions">
   <%= link_to "Edit recipe", edit_recipe_path(@recipe), class: "btn btn-xs btn-warning" %>
   <%= link_to "Delete this recipe", recipe_path(@recipe), method: :delete,
                                     data: { confirm: "Are you sure you want to delete?" },
                                     class: "btn btn-xs btn-danger" %>
   <%= link_to "Return to Recipes", recipes_path, class: "btn btn-xs btn-primary" %>
 </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(obj.errors.count, "error") %>
            prohibited this <%= obj.class %> from being saved:
          </h2>
          <div class="panel-body">
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_page_title.html.erb
<h1 align="center"><%= title %></h1>
<hr />
<br>